apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1  # İstediğiniz sayıda replica belirleyebilirsiniz
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest  # Kullanmak istediğiniz MySQL imajını belirtin
        env:
        - name: MYSQL_ROOT_PASSWORD  # MySQL root parolasını burada belirtin
          value: "dia"  # Güçlü bir parola belirleyin
        ports:
        - containerPort: 3306  # MySQL portu
        command: ["mysqld", "--sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
