apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1  # İstediğiniz sayıda replica belirleyebilirsiniz
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.3.0  # Kullanmak istediğiniz MySQL imajını belirtin
        env:
        - name: MYSQL_ROOT_PASSWORD  # MySQL root parolasını burada belirtin
          value: "dia"  # Güçlü bir parola belirleyin
        ports:
        - containerPort: 3306  # MySQL portu