apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    # SQL Mode Configuration
    sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

    # Packet and Connection Settings
    max_allowed_packet=256M
    connect_timeout=30
    wait_timeout=600
    interactive_timeout=600
    max_connections=100

    # Performance Tuning
    innodb_buffer_pool_size=128M
    innodb_log_file_size=128M
    key_buffer_size=16M

    # Networking
    bind-address=0.0.0.0
    port=3306

    # Logging
    slow_query_log=1
    slow_query_log_file=/var/log/mysql/slow-query.log
    long_query_time=2

    # Security
    local_infile=0
    skip_name_resolve