apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phishupv2-gophish-service
  name: phishupv2-gophish-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phishupv2-gophish-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phishupv2-gophish-service
    spec:
      containers:
        - env:
          - name: ENV
            value: "PROD"
        
          image: phishupacr.azurecr.io/phishupv2-gophish-service:latest
          name: phishupv2-gophish-service
          ports:
            - containerPort: 3333
            - containerPort: 80
          resources: {}
      hostname: phishupv2-gophish-service
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phishupv2-gophish-service
  name: phishupv2-gophish-service
spec:
  type: LoadBalancer
  ports:
    - name: "admin"
      port: 3333
      targetPort: 3333
    - name: "phish"
      port: 80
      targetPort: 80
  selector:
    app: phishupv2-gophish-service